name: Take a look at the I Really Wish I Weren't Here Right Now button
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "REEEEEEEEEEE"
        REMOVE_LABEL: "awaiting%20review"